name: Simple Bybit Test

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Bybit API
      id: test
      run: |
        echo "Testing Bybit API..."
        response=$(curl -s "https://api.bybit.com/v5/public/time")
        echo "Response: $response"
        echo "::set-output name=response::$response"
        
    - name: Comment on issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          const response = '${{ steps.test.outputs.response }}';
          const issue_number = context.issue.number;
          
          await github.rest.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## Bybit API Test\n\n**Response:** ```json\n' + response + '\n```'
          });
