name: Bybit API Proxy

on:
  issues:
    types: [opened]
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  proxy-request:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test Bybit API
      id: test
      run: |
        echo "Testing Bybit API with curl..."
        
        response=$(curl -s "https://api.bybit.com/v5/public/time")
        status_code=$?
        
        echo "Curl exit code: $status_code"
        echo "Response received (length: ${#response})"
        
        if [ $status_code -eq 0 ]; then
          echo "::set-output name=success::true"
          echo "::set-output name=comment::## Bybit API Test Success! Response received successfully."
        else
          echo "::set-output name=success::false"
          echo "::set-output name=comment::## Bybit API Test Failed! Error code: $status_code"
        fi
        
    - name: Comment on issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          const comment = '${{ steps.test.outputs.comment }}';
          const issue_number = context.issue.number;
          
          console.log('Adding comment to issue:', issue_number);
          
          await github.rest.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
          console.log('Comment added successfully!');
