name: Bybit API Proxy

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  proxy-request:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install axios
      run: npm install axios
        
    - name: Process Bybit API request
      id: process-request
      run: |
        echo "Starting Bybit API test..."
        
        node -e "
        const axios = require('axios');
        
        console.log('Testing Bybit API with axios...');
        
        // Тестируем публичный endpoint
        axios.get('https://api.bybit.com/v5/public/time', {
          timeout: 30000,
          headers: {
            'User-Agent': 'GitHub-Actions-Proxy/1.0'
          }
        })
        .then(response => {
          console.log('✅ Success! Status:', response.status);
          console.log('Data:', JSON.stringify(response.data, null, 2));
          
          const comment = \`## ✅ Bybit API Test Success!

**Endpoint:** \`/v5/public/time\`
**Status:** \${response.status}
**Data:** \`\`\`json
\${JSON.stringify(response.data, null, 2)}
\`\`\`

**Timestamp:** \${new Date().toISOString()}
**GitHub Actions:** ✅ Working\`;
          
          console.log('::set-output name=comment::' + comment);
          console.log('::set-output name=success::true');
        })
        .catch(error => {
          console.error('❌ Error:', error.message);
          
          if (error.response) {
            console.error('Response status:', error.response.status);
            console.error('Response data:', error.response.data);
          }
          
          const errorComment = \`## ❌ Bybit API Test Failed

**Error:** \${error.message}
**Status:** \${error.response?.status || 'N/A'}
**Data:** \`\`\`json
\${JSON.stringify(error.response?.data || {}, null, 2)}
\`\`\`

**Timestamp:** \${new Date().toISOString()}
**GitHub Actions:** ❌ Failed\`;
          
          console.log('::set-output name=comment::' + errorComment);
          console.log('::set-output name=success::false');
        });
        "
        
    - name: Show output
      run: |
        echo "Comment output: ${{ steps.process-request.outputs.comment }}"
        echo "Success output: ${{ steps.process-request.outputs.success }}"
        
    - name: Comment on issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          const comment = '${{ steps.process-request.outputs.comment }}';
          const issue_number = context.issue.number;
          
          console.log('Adding comment to issue:', issue_number);
          console.log('Comment length:', comment.length);
          
          await github.rest.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
          console.log('Comment added successfully!');
        
    - name: Show final result
      run: |
        echo "=== FINAL RESULT ==="
        echo "Success: ${{ steps.process-request.outputs.success }}"
        echo "Comment exists: ${{ steps.process-request.outputs.comment != '' }}"
        echo "==================="
