name: Bybit API Test (curl)

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Bybit API
      id: test
      run: |
        echo "Testing Bybit API with curl..."
        
        # Тестируем публичный endpoint
        response=$(curl -s "https://api.bybit.com/v5/public/time")
        status_code=$?
        
        echo "Curl exit code: $status_code"
        echo "Response received (length: ${#response})"
        
        if [ $status_code -eq 0 ]; then
          echo "::set-output name=success::true"
          # Экранируем ответ для безопасного вывода
          safe_response=$(echo "$response" | tr -d '\n' | sed 's/"/\\"/g')
          echo "::set-output name=response::$safe_response"
          echo "::set-output name=comment::## Bybit API Test Success!\n\n**Response:** \`\`\`\n$safe_response\n\`\`\`"
        else
          echo "::set-output name=success::false"
          echo "::set-output name=response::Error: curl failed with code $status_code"
          echo "::set-output name=comment::## Bybit API Test Failed!\n\n**Error:** curl failed with code $status_code"
        fi
        
    - name: Show outputs
      run: |
        echo "Success: ${{ steps.test.outputs.success }}"
        echo "Response length: ${{ steps.test.outputs.response != '' && 'Response exists' || 'No response' }}"
        
    - name: Comment on issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          const comment = '${{ steps.test.outputs.comment }}';
          const issue_number = context.issue.number;
          
          console.log('Adding comment to issue:', issue_number);
          console.log('Comment length:', comment.length);
          
          await github.rest.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
          console.log('Comment added successfully!');
